# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Cargo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('nv_cargo', models.IntegerField(verbose_name='Nível do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'db_table': 'cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_vinculo', models.DateField(verbose_name='Data do vínculo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('cod_compra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'db_table': 'compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('cod_contato', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do contato')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('cpf_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'db_table': 'contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('cod_estoque', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do estoque')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('dt_atu', models.DateField(verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Estoque',
                'db_table': 'estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_vinculo', models.DateField(verbose_name='Data do vínculo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'db_table': 'fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cod_funcionario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do funcionario')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('dt_inicio', models.DateField(verbose_name='Data de início')),
                ('dt_fim', models.DateField(null=True, verbose_name='Data de fim')),
                ('salario', models.IntegerField(verbose_name='Salário')),
                ('cod_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'db_table': 'funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('cod_oper', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da operação')),
                ('dt_oper', models.DateField(verbose_name='Data da operação')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('cod_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Funcionario')),
            ],
            options={
                'verbose_name': 'Operação',
                'db_table': 'operacao',
                'verbose_name_plural': 'Operações',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da pedido')),
                ('cliente_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'db_table': 'pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_produto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do produto')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('data_validade', models.DateField(verbose_name='Data de validade')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('num_lote', models.IntegerField(verbose_name='Número do lote')),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('cod_tp_contrato', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do tipo de contrato')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'db_table': 'tipo_contrato',
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='TpProduto',
            fields=[
                ('cod_tp_produto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código do tipo do produto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'db_table': 'tp_produto',
                'verbose_name_plural': 'Tipos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('cod_venda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da venda')),
                ('cod_oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Operacao')),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Pedido')),
            ],
            options={
                'verbose_name': 'Venda',
                'db_table': 'venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='cod_tp_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.TpProduto'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='cod_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Produto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cod_tp_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.TipoContrato'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cod_oper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Operacao'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketfy.Fornecedor'),
        ),
    ]
